### ISSUE TITLE
Evaluar Mercado Liebre/ Aynelen Ledesma

### ISSUE THREAD

**Issue by AynelenLedesma** [martinatia/mercadoLiebre-MartinAtia#1]
- [x] 1- Cumple
- [x] 2- Cumple
- [x] 3- Cumple los iconos 2em. No cumple el margen por que no tiene margen.
- [x] 4- Cumple
- [x] 5- Cumple
- [x] 6- Cumple
- [x] 7- Cumple
- [x] 8- Cumple
- [x] 9- El Home, esta muy bien hecho, de acuerdo a todo lo que  piden
- [x] 10- El Registro y login falta terminar, de colocarle el footer para poder ver en distintos tamaños de pantalla. Las barra de búsqueda  y logo están muy pequeña en home , resgistro y login.

**Comment by martinatia** [comment]
9- El Home, esta muy bien hecho, de acuerdo a todo lo que NO piden. -> No entiendo que significa esto

**Comment by martinatia** [comment]
Corregido.
Saludos
