### ISSUE TITLE
Evaluar Mercado Liebre/ Mauro Rodriguez

### ISSUE THREAD

**Issue by maurodriguez53199** [martinatia/mercadoLiebre-MartinAtia#2]
- [x] Cumple
- [x] Cumple
- [x] Los iconos tienen tamaño 2em, no tienen margen que cumplir.
- [x] Cumple
- [x] Cumple
- [x] Cumple
- [x] Cumple
- [x] Cumple
- [x] Bien realizado el login y sing up.
- [x] Falta footer en registro y login.

**Comment by martinatia** [comment]
Corregido.
Saludos
